// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/getArea/getArea.proto

package go_micro_srv_getArea

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d5f419fc6d540c0, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	Errno                string      `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg               string      `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Data                 []*AreaInfo `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d5f419fc6d540c0, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *Response) GetData() []*AreaInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type AreaInfo struct {
	Aid                  int32    `protobuf:"varint,1,opt,name=aid,proto3" json:"aid,omitempty"`
	Aname                string   `protobuf:"bytes,2,opt,name=aname,proto3" json:"aname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AreaInfo) Reset()         { *m = AreaInfo{} }
func (m *AreaInfo) String() string { return proto.CompactTextString(m) }
func (*AreaInfo) ProtoMessage()    {}
func (*AreaInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d5f419fc6d540c0, []int{2}
}

func (m *AreaInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaInfo.Unmarshal(m, b)
}
func (m *AreaInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaInfo.Marshal(b, m, deterministic)
}
func (m *AreaInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaInfo.Merge(m, src)
}
func (m *AreaInfo) XXX_Size() int {
	return xxx_messageInfo_AreaInfo.Size(m)
}
func (m *AreaInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AreaInfo proto.InternalMessageInfo

func (m *AreaInfo) GetAid() int32 {
	if m != nil {
		return m.Aid
	}
	return 0
}

func (m *AreaInfo) GetAname() string {
	if m != nil {
		return m.Aname
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.getArea.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.getArea.Response")
	proto.RegisterType((*AreaInfo)(nil), "go.micro.srv.getArea.AreaInfo")
}

func init() { proto.RegisterFile("proto/getArea/getArea.proto", fileDescriptor_3d5f419fc6d540c0) }

var fileDescriptor_3d5f419fc6d540c0 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x3d, 0x4b, 0xc5, 0x30,
	0x14, 0x86, 0xbd, 0xd6, 0x7b, 0x6f, 0x7b, 0x74, 0x90, 0x50, 0xa4, 0x28, 0x96, 0x92, 0xa9, 0x53,
	0x84, 0xf8, 0x0b, 0x9c, 0xc4, 0x41, 0x84, 0x8c, 0x6e, 0xd1, 0x1e, 0x4b, 0xc1, 0x26, 0xf5, 0x24,
	0xfa, 0xfb, 0x25, 0x1f, 0xdd, 0x7a, 0x97, 0x24, 0xcf, 0x7b, 0x42, 0x1e, 0xde, 0xc0, 0xdd, 0x42,
	0xd6, 0xdb, 0x87, 0x11, 0xfd, 0x13, 0xa1, 0x5e, 0x77, 0x11, 0x53, 0x56, 0x8f, 0x56, 0xcc, 0xd3,
	0x27, 0x59, 0xe1, 0xe8, 0x4f, 0xe4, 0x19, 0xaf, 0xe0, 0xa8, 0xf0, 0xe7, 0x17, 0x9d, 0xe7, 0xdf,
	0x50, 0x2a, 0x74, 0x8b, 0x35, 0x0e, 0x59, 0x0d, 0x7b, 0x24, 0x32, 0xb6, 0xd9, 0x75, 0xbb, 0xbe,
	0x52, 0x09, 0xd8, 0x0d, 0x1c, 0x90, 0x68, 0x76, 0x63, 0x73, 0x1e, 0xe3, 0x4c, 0x4c, 0xc2, 0xc5,
	0xa0, 0xbd, 0x6e, 0x8a, 0xae, 0xe8, 0x2f, 0x65, 0x2b, 0xb6, 0x4c, 0x22, 0x2c, 0x2f, 0xe6, 0xcb,
	0xaa, 0x78, 0x97, 0x4b, 0x28, 0xd7, 0x84, 0x5d, 0x43, 0xa1, 0xa7, 0x21, 0xba, 0xf6, 0x2a, 0x1c,
	0x83, 0x5f, 0x1b, 0x3d, 0x63, 0x16, 0x25, 0x90, 0xef, 0x70, 0x7c, 0x4e, 0xaf, 0xb1, 0x37, 0xb8,
	0x7a, 0x0d, 0x8a, 0x95, 0xef, 0xb7, 0xa5, 0xb9, 0xdb, 0x6d, 0x7b, 0x6a, 0x9c, 0xfa, 0xf2, 0xb3,
	0x8f, 0x43, 0xfc, 0xa5, 0xc7, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x71, 0x63, 0xe7, 0x44,
	0x01, 0x00, 0x00,
}
