// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/userOrder/userOrder.proto

package go_micro_srv_userOrder

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateReq struct {
	Action               string   `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateReq) Reset()         { *m = UpdateReq{} }
func (m *UpdateReq) String() string { return proto.CompactTextString(m) }
func (*UpdateReq) ProtoMessage()    {}
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_deaaec7ecd8f1384, []int{0}
}

func (m *UpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReq.Unmarshal(m, b)
}
func (m *UpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReq.Marshal(b, m, deterministic)
}
func (m *UpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReq.Merge(m, src)
}
func (m *UpdateReq) XXX_Size() int {
	return xxx_messageInfo_UpdateReq.Size(m)
}
func (m *UpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReq proto.InternalMessageInfo

func (m *UpdateReq) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *UpdateReq) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *UpdateReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateResp struct {
	Errno                string   `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResp) Reset()         { *m = UpdateResp{} }
func (m *UpdateResp) String() string { return proto.CompactTextString(m) }
func (*UpdateResp) ProtoMessage()    {}
func (*UpdateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_deaaec7ecd8f1384, []int{1}
}

func (m *UpdateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResp.Unmarshal(m, b)
}
func (m *UpdateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResp.Marshal(b, m, deterministic)
}
func (m *UpdateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResp.Merge(m, src)
}
func (m *UpdateResp) XXX_Size() int {
	return xxx_messageInfo_UpdateResp.Size(m)
}
func (m *UpdateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResp proto.InternalMessageInfo

func (m *UpdateResp) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *UpdateResp) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

type GetReq struct {
	Role                 string   `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReq) Reset()         { *m = GetReq{} }
func (m *GetReq) String() string { return proto.CompactTextString(m) }
func (*GetReq) ProtoMessage()    {}
func (*GetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_deaaec7ecd8f1384, []int{2}
}

func (m *GetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReq.Unmarshal(m, b)
}
func (m *GetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReq.Marshal(b, m, deterministic)
}
func (m *GetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReq.Merge(m, src)
}
func (m *GetReq) XXX_Size() int {
	return xxx_messageInfo_GetReq.Size(m)
}
func (m *GetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetReq proto.InternalMessageInfo

func (m *GetReq) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *GetReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type GetResp struct {
	Errno                string   `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Data                 *GetData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResp) Reset()         { *m = GetResp{} }
func (m *GetResp) String() string { return proto.CompactTextString(m) }
func (*GetResp) ProtoMessage()    {}
func (*GetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_deaaec7ecd8f1384, []int{3}
}

func (m *GetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResp.Unmarshal(m, b)
}
func (m *GetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResp.Marshal(b, m, deterministic)
}
func (m *GetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResp.Merge(m, src)
}
func (m *GetResp) XXX_Size() int {
	return xxx_messageInfo_GetResp.Size(m)
}
func (m *GetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetResp proto.InternalMessageInfo

func (m *GetResp) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *GetResp) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *GetResp) GetData() *GetData {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetData struct {
	Orders               []*OrdersData `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetData) Reset()         { *m = GetData{} }
func (m *GetData) String() string { return proto.CompactTextString(m) }
func (*GetData) ProtoMessage()    {}
func (*GetData) Descriptor() ([]byte, []int) {
	return fileDescriptor_deaaec7ecd8f1384, []int{4}
}

func (m *GetData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetData.Unmarshal(m, b)
}
func (m *GetData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetData.Marshal(b, m, deterministic)
}
func (m *GetData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetData.Merge(m, src)
}
func (m *GetData) XXX_Size() int {
	return xxx_messageInfo_GetData.Size(m)
}
func (m *GetData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetData.DiscardUnknown(m)
}

var xxx_messageInfo_GetData proto.InternalMessageInfo

func (m *GetData) GetOrders() []*OrdersData {
	if m != nil {
		return m.Orders
	}
	return nil
}

type OrdersData struct {
	Amount               int32    `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Comment              string   `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	Ctime                string   `protobuf:"bytes,3,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Days                 int32    `protobuf:"varint,4,opt,name=days,proto3" json:"days,omitempty"`
	EndDate              string   `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	ImgUrl               string   `protobuf:"bytes,6,opt,name=img_url,json=imgUrl,proto3" json:"img_url,omitempty"`
	OrderId              int32    `protobuf:"varint,7,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	StartDate            string   `protobuf:"bytes,8,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	Status               string   `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	Title                string   `protobuf:"bytes,10,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrdersData) Reset()         { *m = OrdersData{} }
func (m *OrdersData) String() string { return proto.CompactTextString(m) }
func (*OrdersData) ProtoMessage()    {}
func (*OrdersData) Descriptor() ([]byte, []int) {
	return fileDescriptor_deaaec7ecd8f1384, []int{5}
}

func (m *OrdersData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrdersData.Unmarshal(m, b)
}
func (m *OrdersData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrdersData.Marshal(b, m, deterministic)
}
func (m *OrdersData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrdersData.Merge(m, src)
}
func (m *OrdersData) XXX_Size() int {
	return xxx_messageInfo_OrdersData.Size(m)
}
func (m *OrdersData) XXX_DiscardUnknown() {
	xxx_messageInfo_OrdersData.DiscardUnknown(m)
}

var xxx_messageInfo_OrdersData proto.InternalMessageInfo

func (m *OrdersData) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *OrdersData) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *OrdersData) GetCtime() string {
	if m != nil {
		return m.Ctime
	}
	return ""
}

func (m *OrdersData) GetDays() int32 {
	if m != nil {
		return m.Days
	}
	return 0
}

func (m *OrdersData) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *OrdersData) GetImgUrl() string {
	if m != nil {
		return m.ImgUrl
	}
	return ""
}

func (m *OrdersData) GetOrderId() int32 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *OrdersData) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *OrdersData) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OrdersData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type Request struct {
	HouseId              string   `protobuf:"bytes,1,opt,name=house_id,json=houseId,proto3" json:"house_id,omitempty"`
	StartDate            string   `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              string   `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	UserName             string   `protobuf:"bytes,4,opt,name=userName,proto3" json:"userName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_deaaec7ecd8f1384, []int{6}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetHouseId() string {
	if m != nil {
		return m.HouseId
	}
	return ""
}

func (m *Request) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *Request) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *Request) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type Response struct {
	Errno                string     `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg               string     `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Data                 *OrderData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_deaaec7ecd8f1384, []int{7}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *Response) GetData() *OrderData {
	if m != nil {
		return m.Data
	}
	return nil
}

type OrderData struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderData) Reset()         { *m = OrderData{} }
func (m *OrderData) String() string { return proto.CompactTextString(m) }
func (*OrderData) ProtoMessage()    {}
func (*OrderData) Descriptor() ([]byte, []int) {
	return fileDescriptor_deaaec7ecd8f1384, []int{8}
}

func (m *OrderData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderData.Unmarshal(m, b)
}
func (m *OrderData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderData.Marshal(b, m, deterministic)
}
func (m *OrderData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderData.Merge(m, src)
}
func (m *OrderData) XXX_Size() int {
	return xxx_messageInfo_OrderData.Size(m)
}
func (m *OrderData) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderData.DiscardUnknown(m)
}

var xxx_messageInfo_OrderData proto.InternalMessageInfo

func (m *OrderData) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func init() {
	proto.RegisterType((*UpdateReq)(nil), "go.micro.srv.userOrder.UpdateReq")
	proto.RegisterType((*UpdateResp)(nil), "go.micro.srv.userOrder.UpdateResp")
	proto.RegisterType((*GetReq)(nil), "go.micro.srv.userOrder.GetReq")
	proto.RegisterType((*GetResp)(nil), "go.micro.srv.userOrder.GetResp")
	proto.RegisterType((*GetData)(nil), "go.micro.srv.userOrder.GetData")
	proto.RegisterType((*OrdersData)(nil), "go.micro.srv.userOrder.OrdersData")
	proto.RegisterType((*Request)(nil), "go.micro.srv.userOrder.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.userOrder.Response")
	proto.RegisterType((*OrderData)(nil), "go.micro.srv.userOrder.OrderData")
}

func init() { proto.RegisterFile("proto/userOrder/userOrder.proto", fileDescriptor_deaaec7ecd8f1384) }

var fileDescriptor_deaaec7ecd8f1384 = []byte{
	// 524 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x51, 0x8b, 0x13, 0x31,
	0x10, 0xbe, 0x6e, 0xdb, 0xdd, 0xee, 0xf4, 0xf0, 0x21, 0x48, 0x8d, 0x05, 0x6d, 0xcd, 0x83, 0xdc,
	0xd3, 0x0a, 0x3d, 0x04, 0xb9, 0x57, 0x4f, 0xca, 0x21, 0x28, 0xae, 0x14, 0x1f, 0x4b, 0xec, 0x8e,
	0x75, 0xa1, 0xbb, 0x69, 0x93, 0xac, 0xa0, 0xcf, 0xbe, 0xf9, 0xa7, 0x25, 0x93, 0xb4, 0xd7, 0x9e,
	0xb6, 0xc7, 0xbd, 0x94, 0x7c, 0x93, 0xcc, 0x37, 0x33, 0xdf, 0x7c, 0x5d, 0x18, 0xad, 0xb5, 0xb2,
	0xea, 0x55, 0x63, 0x50, 0x7f, 0xd4, 0x05, 0xea, 0xdb, 0x53, 0x46, 0x37, 0x6c, 0xb0, 0x54, 0x59,
	0x55, 0x2e, 0xb4, 0xca, 0x8c, 0xfe, 0x91, 0xed, 0x6e, 0xc5, 0x7b, 0x48, 0x67, 0xeb, 0x42, 0x5a,
	0xcc, 0x71, 0xc3, 0x06, 0x10, 0xcb, 0x85, 0x2d, 0x55, 0xcd, 0x5b, 0xe3, 0xd6, 0x45, 0x9a, 0x07,
	0xe4, 0xe2, 0x1a, 0xa5, 0x51, 0x35, 0x8f, 0x7c, 0xdc, 0x23, 0xf6, 0x08, 0xa2, 0xb2, 0xe0, 0x6d,
	0x8a, 0x45, 0x65, 0x21, 0xae, 0x00, 0xb6, 0x64, 0x66, 0xcd, 0x1e, 0x43, 0x17, 0xb5, 0xae, 0x55,
	0x20, 0xf3, 0xc0, 0x71, 0xa1, 0xd6, 0x95, 0x59, 0x6e, 0xb9, 0x3c, 0x12, 0x6f, 0x20, 0x9e, 0xa2,
	0x75, 0x5d, 0x30, 0xe8, 0x68, 0xb5, 0xc2, 0x90, 0x46, 0x67, 0x36, 0x84, 0x9e, 0xeb, 0xf9, 0x83,
	0xac, 0x30, 0xe4, 0xed, 0xb0, 0x58, 0x41, 0x42, 0x99, 0x0f, 0x2d, 0xc9, 0x2e, 0xa1, 0x53, 0x48,
	0x2b, 0x69, 0x80, 0xfe, 0x64, 0x94, 0xfd, 0x5f, 0xa2, 0x6c, 0x8a, 0xf6, 0x5a, 0x5a, 0x99, 0xd3,
	0x63, 0xf1, 0x8e, 0xaa, 0xb9, 0x00, 0xbb, 0x82, 0x58, 0xb9, 0x17, 0x86, 0xb7, 0xc6, 0xed, 0x8b,
	0xfe, 0x44, 0x1c, 0x63, 0xa0, 0x5f, 0x43, 0x24, 0x21, 0x43, 0xfc, 0x8e, 0x00, 0x6e, 0xc3, 0xa4,
	0x7c, 0xa5, 0x9a, 0xda, 0x52, 0xe7, 0xdd, 0x3c, 0x20, 0xc6, 0x21, 0x59, 0xa8, 0xaa, 0xc2, 0xda,
	0x86, 0xde, 0xb7, 0xd0, 0x8d, 0xba, 0xb0, 0x65, 0x85, 0x41, 0x7e, 0x0f, 0x9c, 0x76, 0x85, 0xfc,
	0x69, 0x78, 0x87, 0x58, 0xe8, 0xcc, 0x9e, 0x42, 0x0f, 0xeb, 0x62, 0xee, 0xf6, 0xc2, 0xbb, 0x9e,
	0x04, 0xeb, 0xe2, 0x5a, 0x5a, 0x64, 0x4f, 0x20, 0x29, 0xab, 0xe5, 0xbc, 0xd1, 0x2b, 0x1e, 0x7b,
	0x69, 0xca, 0x6a, 0x39, 0xd3, 0x2b, 0x97, 0x43, 0x8d, 0xce, 0xcb, 0x82, 0x27, 0xc4, 0x95, 0x10,
	0xbe, 0x29, 0xd8, 0x33, 0x00, 0x63, 0xa5, 0xb6, 0x9e, 0xb0, 0x47, 0x69, 0x29, 0x45, 0x88, 0x72,
	0x00, 0xb1, 0xb1, 0xd2, 0x36, 0x86, 0xa7, 0x9e, 0xd1, 0x23, 0xd7, 0xaf, 0x2d, 0xed, 0x0a, 0x39,
	0xf8, 0x7e, 0x09, 0x88, 0x5f, 0x90, 0xe4, 0xb8, 0x69, 0xd0, 0x58, 0x57, 0xf2, 0xbb, 0x6a, 0x0c,
	0xba, 0x92, 0x7e, 0x7d, 0x09, 0xe1, 0x7f, 0x4a, 0x46, 0x77, 0x4b, 0xee, 0x0f, 0xd8, 0x3e, 0x1c,
	0x70, 0xdf, 0x37, 0x9d, 0x3b, 0xbe, 0x51, 0xd0, 0x73, 0xa6, 0x51, 0xb5, 0xc1, 0x07, 0x1a, 0xe7,
	0xf5, 0x81, 0x71, 0x5e, 0x9c, 0x5c, 0xfb, 0x9e, 0x75, 0x5e, 0x42, 0xba, 0x0b, 0x1d, 0x28, 0x1c,
	0xc6, 0x0d, 0x0a, 0x4f, 0xfe, 0x44, 0x90, 0xce, 0xb6, 0x2c, 0x2c, 0x87, 0xfe, 0x5b, 0x8d, 0xd2,
	0xa2, 0x87, 0x47, 0x6d, 0x1a, 0x74, 0x1c, 0x8e, 0x8f, 0x3f, 0xf0, 0xc3, 0x8a, 0x33, 0xf6, 0x09,
	0xce, 0xa7, 0x68, 0x29, 0x7c, 0x53, 0x7f, 0x53, 0xec, 0xf9, 0x09, 0xef, 0xe7, 0xb8, 0x19, 0x8e,
	0x4e, 0xde, 0x9b, 0xb5, 0x38, 0x63, 0x5f, 0xe0, 0xdc, 0xff, 0xf7, 0x3f, 0xfb, 0x7d, 0x1f, 0x55,
	0x65, 0xf7, 0xb9, 0x19, 0x8a, 0xfb, 0x9e, 0x38, 0xe2, 0xaf, 0x31, 0x7d, 0xc0, 0x2e, 0xff, 0x06,
	0x00, 0x00, 0xff, 0xff, 0x65, 0x74, 0xee, 0x37, 0xe3, 0x04, 0x00, 0x00,
}
